[toolchain]
lic_repo = "https://github.com/li-langverse/lic"
lic_version = "studio-demo-2026-05-24"
lit_repo = "https://github.com/li-langverse/lit"
lit_version = "0.0.1"

[coverage]
min_coverage = 80
