#!/usr/bin/env bash
# Interactive lip registry login — stores API token in ~/.config/lip/credentials.toml
#
# Usage (from lip/):
#   ./scripts/lip-login.sh
#
# Env:
#   LIP_REGISTRY_URL   — override prompted registry base (without /v1)
#   LI_JWT_SECRET      — must match server (not needed client-side for API token flow)
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/lip"
CRED_FILE="$CONFIG_DIR/credentials.toml"

normalize_registry_url() {
  local url="${1%/}"
  if [[ "$url" == */v1 ]]; then
    echo "${url%/v1}"
  else
    echo "$url"
  fi
}

api_base() {
  local base
  base="$(normalize_registry_url "$1")"
  echo "${base}/v1"
}

prompt_registry_url() {
  local default="${LIP_REGISTRY_URL:-http://127.0.0.1:54321}"
  local url
  read -r -p "Registry URL [${default}]: " url
  url="${url:-$default}"
  normalize_registry_url "$url"
}

prompt_secret() {
  local var="$1" prompt="$2" value
  read -r -s -p "$prompt: " value
  echo >&2
  printf -v "$var" '%s' "$value"
}

json_post() {
  local url="$1" body="$2" token="${3:-}"
  local tmp
  tmp="$(mktemp)"
  local code
  if [[ -n "$token" ]]; then
    code="$(curl -sS -o "$tmp" -w "%{http_code}" -X POST "$url" \
      -H "Content-Type: application/json" \
      -H "Authorization: Bearer $token" \
      -d "$body")"
  else
    code="$(curl -sS -o "$tmp" -w "%{http_code}" -X POST "$url" \
      -H "Content-Type: application/json" \
      -d "$body")"
  fi
  echo "$code" "$tmp"
}

extract_json_field() {
  python3 - "$1" "$2" <<'PY'
import json, sys
path, key = sys.argv[1], sys.argv[2]
with open(path, encoding="utf-8") as f:
    data = json.load(f)
keys = key.split(".")
cur = data
for k in keys:
    if not isinstance(cur, dict) or k not in cur:
        sys.exit(1)
    cur = cur[k]
print(cur)
PY
}

write_credentials() {
  local registry_url="$1" token="$2" email="$3"
  mkdir -p "$CONFIG_DIR"
  chmod 700 "$CONFIG_DIR"
  cat >"$CRED_FILE" <<EOF
# Generated by lip-login.sh — do not commit
[registry]
url = "${registry_url}/v1"
token = "${token}"
email = "${email}"
EOF
  chmod 600 "$CRED_FILE"
}

main() {
  if ! command -v curl >/dev/null 2>&1; then
    echo "lip-login: curl required" >&2
    exit 1
  fi

  local registry_base api email password session_body session_file session_code
  local session_token token_body token_file token_code api_token

  registry_base="$(prompt_registry_url)"
  api="$(api_base "$registry_base")"

  echo "lip-login: registry ${api}"
  echo "lip-login: choose login method"
  echo "  1) Email + password (MVP)"
  echo "  2) Use existing API token"
  echo "  3) Device code (not available — falls back to email)"
  local choice
  read -r -p "Choice [1]: " choice
  choice="${choice:-1}"

  if [[ "$choice" == "2" ]]; then
    prompt_secret api_token "API token (lip_…)"
    read -r -p "Email (for credentials.toml) [optional]: " email
    write_credentials "$registry_base" "$api_token" "${email:-}"
    echo "lip-login: saved $CRED_FILE"
    exit 0
  fi

  if [[ "$choice" == "3" ]]; then
    echo "lip-login: device code flow is Phase 1 — opening browser not implemented yet." >&2
    echo "lip-login: use email+password for now." >&2
  fi

  read -r -p "Email: " email
  prompt_secret password "Password"

  session_body="$(python3 - "$email" "$password" <<'PY'
import json, sys
print(json.dumps({"email": sys.argv[1], "password": sys.argv[2]}))
PY
)"
  read -r session_code session_file < <(json_post "${api}/auth/login" "$session_body")
  if [[ "$session_code" != "200" ]]; then
    echo "lip-login: login failed (HTTP $session_code)" >&2
    cat "$session_file" >&2
    rm -f "$session_file"
    exit 1
  fi
  session_token="$(extract_json_field "$session_file" "access_token")"
  rm -f "$session_file"

  token_body='{"name":"lip-cli","scope":"publish+yank"}'
  read -r token_code token_file < <(json_post "${api}/auth/tokens" "$token_body" "$session_token")
  if [[ "$token_code" != "201" ]]; then
    echo "lip-login: token create failed (HTTP $token_code)" >&2
    cat "$token_file" >&2
    rm -f "$token_file"
    exit 1
  fi
  api_token="$(extract_json_field "$token_file" "token")"
  rm -f "$token_file"

  write_credentials "$registry_base" "$api_token" "$email"
  echo "lip-login: saved $CRED_FILE"
  echo "lip-login: export LIP_REGISTRY_TOKEN from credentials or source in scripts"
}

main "$@"
